routes/admin.php
<?php

/* dashboard routes */
Route::get('/', function () {
    return redirect('/admin/dashboard');
});

/* dashboard */
Route::get('/dashboard', [
    'uses' => '\App\Http\Controllers\AdminDashboardController@index',
    'as' => 'admin.dashboard',
]);
/* dashboard */

/* users */
Route::get('/users/draw',
    ['as' => 'admin.users.draw',
        'uses' => '\App\Http\Controllers\UserController@draw']
);

Route::resource('/users', 'UserController', [
    'as' => 'admin'
]);

Route::delete('/users/{id}/delete',
    ['as' => 'admin.users.delete',
        'uses' => '\App\Http\Controllers\UserController@destroy']
);
/* users */

/* roles */
Route::resource('/roles', 'RoleController', [
    'as' => 'admin'
]);

Route::delete('/roles/{id}/delete',
    ['as' => 'admin.roles.delete',
        'uses' => '\App\Http\Controllers\RoleController@destroy']
);
/* roles */

/* permissions */
Route::resource('/permissions', 'PermissionController', [
    'as' => 'admin'
]);

Route::delete('/permissions/{id}/delete',
    ['as' => 'admin.permissions.delete',
        'uses' => '\App\Http\Controllers\PermissionController@destroy']
);
/* permissions */

/* permission groups */
Route::resource('/permission_groups', 'PermissionGroupController', [
    'as' => 'admin'
]);

Route::delete('/permission_groups/{id}/delete',
    ['as' => 'admin.permission_groups.delete',
        'uses' => '\App\Http\Controllers\PermissionGroupController@destroy']
);
/* permission groups */

/* system settings */
Route::resource('/system_settings', 'SystemSettingController', [
    'as' => 'admin',
]);

Route::delete('/system_settings/{id}/delete',
    ['as' => 'admin.system_settings.delete',
        'uses' => '\App\Http\Controllers\SystemSettingController@destroy']
);
/* system settings */

/* posts */
Route::resource('/posts', 'PostController', [
    'as' => 'admin'
]);

Route::delete('/posts/{id}/delete',
    ['as' => 'admin.posts.delete',
        'uses' => '\App\Http\Controllers\PostController@destroy']
);
/* posts */

/* pages */
Route::resource('/pages', 'PageController', [
    'as' => 'admin'
]);

Route::delete('/pages/{id}/delete',
    ['as' => 'admin.pages.delete',
        'uses' => '\App\Http\Controllers\PageController@destroy']
);
/* pages */

/* ckeditor image upload */
Route::post('/ckeditor_image_upload',
    ['as' => 'admin.ckeditor_image_upload',
        'uses' => '\App\Http\Controllers\PageController@ckEditorImageUpload']
);
/* ckeditor image upload */

Route::post('/upload', '\App\Http\Controllers\PageController@upload')->name('admin.upload');

/* home_slides */
Route::resource('/home_slides', 'HomeSlideController', [
    'as' => 'admin'
]);

Route::delete('/home_slides/{id}/delete',
    ['as' => 'admin.home_slides.delete',
        'uses' => '\App\Http\Controllers\HomeSlideController@destroy']
);
/* home_slides */

/* news_press */
Route::resource('/news_press', 'NewsPressController', [
    'as' => 'admin'
]);

Route::delete('/news_press/{id}/delete',
    ['as' => 'admin.news_press.delete',
        'uses' => '\App\Http\Controllers\NewsPressController@destroy']
);
/* news_press */

/* projct_case_study */
Route::resource('/projct_case_study', 'ProjectCaseController', [
    'as' => 'admin'
]);

Route::delete('/projct_case_study/{id}/delete',
    ['as' => 'admin.projct_case_study.delete',
        'uses' => '\App\Http\Controllers\ProjectCaseController@destroy']
);
/* projct_case_study */

/* ser_sol */
Route::resource('/ser_sol', 'ServiceSolutionController', [
    'as' => 'admin'
]);

Route::delete('/ser_sol/{id}/delete',
    ['as' => 'admin.ser_sol.delete',
        'uses' => '\App\Http\Controllers\ServiceSolutionController@destroy']
);
/* ser_sol */

/* products */
Route::resource('/products', 'ProductController', [
    'as' => 'admin'
]);

Route::delete('/products/{id}/delete',
    ['as' => 'admin.products.delete',
        'uses' => '\App\Http\Controllers\ProductController@destroy']
);
/* products */

/* product categories */
Route::resource('/product_categories', 'ProductCategoryController', [
    'as' => 'admin'
]);

Route::delete('/product_categories/{id}/delete',
    ['as' => 'admin.product_categories.delete',
        'uses' => '\App\Http\Controllers\ProductCategoryController@destroy']
);
/* product categories */

/* contacts */
Route::resource('/contacts', 'ContactController', [
    'as' => 'admin'
]);

Route::delete('/contacts/{id}/delete',
    ['as' => 'admin.contacts.delete',
        'uses' => '\App\Http\Controllers\ContactController@destroy']
);
/* contacts */

/* presses */


/*Route::resource('/faqs', 'FAQController', [
    'as' => 'admin'
]);

*/


/* projects */
        Route::resource('/projects', 'ProjectController', [
            'as' => 'admin'
        ]);

Route::delete('/projects/{id}/delete',
            ['as' => 'admin.projects.delete',
                'uses' => '\App\Http\Controllers\ProjectController@destroy']
        );
        /* projects */

/* services */
        Route::resource('/services', 'ServiceController', [
            'as' => 'admin'
        ]);

Route::delete('/services/{id}/delete',
            ['as' => 'admin.services.delete',
                'uses' => '\App\Http\Controllers\ServiceController@destroy']
        );
        /* services */

/* news */
        Route::resource('/news', 'NewsController', [
            'as' => 'admin'
        ]);

Route::delete('/news/{id}/delete',
            ['as' => 'admin.news.delete',
                'uses' => '\App\Http\Controllers\NewsController@destroy']
        );
        /* news */

/* leaderships */
        Route::resource('/leaderships', 'LeadershipController', [
            'as' => 'admin'
        ]);

Route::delete('/leaderships/{id}/delete',
            ['as' => 'admin.leaderships.delete',
                'uses' => '\App\Http\Controllers\LeadershipController@destroy']
        );
        /* leaderships */

/* newscategories */
        Route::resource('/newscategories', 'NewsCategoryController', [
            'as' => 'admin'
        ]);

Route::delete('/newscategories/{id}/delete',
            ['as' => 'admin.newscategories.delete',
                'uses' => '\App\Http\Controllers\NewsCategoryController@destroy']
        );
        /* newscategories */

routes/web.php
<?php
use Illuminate\Http\Request;
use App\Models\Project;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/re_order_proeject', function(Request $request) {

    $order = $request->data;

    $get_project = new Project();

    // $project_all = $get_project::all();

    $counter = 1;

    foreach($order as $proj)
    {
        $get_project::find($proj)->update(['order' => $counter]);
        $counter++;
    }

    // return $project_all;
    
});

resources/views/admin/pages/faq/create.blade.php
@extends('admin.layouts.base')

@section('content')
    <ul class="breadcrumb breadcrumb-top">
       <li><a href="{{ route('admin.faqs.index', $id) }}">FAQ's</a></li>
        <li><span href="javascript:void(0)">Add New FAQ</span></li>
    </ul>
    <div class="row">
        {{  Form::open([
            'method' => 'POST',
            'id' => 'create-faq',
            'route' => ['admin.faqs.store', $id],
            'class' => 'form-horizontal ',
            'files' => TRUE
            ])
        }}
        <div class="col-md-12">
            <div class="block">
                <div class="block-title">
                    <h2><i class="fa fa-pencil"></i> <strong>Add new FAQ</strong></h2>
                </div>


                <div class="form-group{{ $errors->has('FAQQuestion') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label" for="FAQQuestion">Question</label>

                    <div class="col-md-9">
                        <textarea id="FAQQuestion" name="FAQQuestion" rows="9"
                                  class="form-control" placeholder="Enter FAQ question..">{{ old('FAQQuestion') }}</textarea>
                        @if($errors->has('FAQQuestion'))
                            <span class="help-block animation-slideDown">{{ $errors->first('FAQQuestion') }}</span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('FAQAnswer') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label" for="FAQAnswer">Answer</label>

                    <div class="col-md-9">
                        <textarea id="FAQQuestion" name="FAQAnswer" rows="9"
                                  class="form-control" placeholder="Enter FAQ answer..">{{ old('FAQAnswer') }}</textarea>
                        @if($errors->has('FAQAnswer'))
                            <span class="help-block animation-slideDown">{{ $errors->first('FAQAnswer') }}</span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('FAQVideoTag') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label" for="FAQVideoTag">Video Tag</label>

                    <div class="col-md-9">
                        <input type="text" class="form-control" id="FAQVideoTag" name="FAQVideoTag"
                               placeholder="Enter FAQ videotag.." value="{{ old('FAQVideoTag') }}">
                        @if($errors->has('FAQVideoTag'))
                            <span class="help-block animation-slideDown">{{ $errors->first('FAQVideoTag') }}</span>
                        @endif
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-3 control-label">Is Enabled?</label>

                    <div class="col-md-9">
                        <label class="switch switch-primary">
                            <input type="checkbox" id="FAQEnabled" name="FAQEnabled"
                                   value="1" checked>
                            <span></span>
                        </label>
                    </div>
                </div>

                <div class="form-group form-actions">
                    <div class="col-md-9 col-md-offset-3">
                        <a href="{{ route('admin.faqs.index', $id) }}" class="btn btn-sm btn-warning">Cancel</a>
                        <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-floppy-o"></i> Save
                        </button>
                    </div>
                </div>
            </div>
        </div>
        {{ Form::close() }}
    </div>
@endsection

@push('extrascripts')
    <script type="text/javascript" src="{{ asset('public/js/ckeditor/ckeditor.js') }}"></script>
    <script type="text/javascript" src="{{ asset('public/js/libraries/faqs.js') }}"></script>
@endpush

resources/views/admin/pages/faq/edit.blade.php
@extends('admin.layouts.base')

@section('content')
    <ul class="breadcrumb breadcrumb-top">
        <li><a href="{{ route('admin.faqs.index', $faq->FAQTypeID) }}">FAQ's</a></li>
        <li><span href="javascript:void(0)">Edit FAQ</span></li>
    </ul>
    <div class="row">
        {{  Form::open([
            'method' => 'PUT',
            'id' => 'edit-press',
            'route' => ['admin.faqs.update', $faq->FAQID],
            'class' => 'form-horizontal ',
            'files' => TRUE
            ])
        }}
        <div class="col-md-12">
            <div class="block">
                <div class="block-title">
                    <h2><i class="fa fa-pencil"></i> <strong>Edit FAQ "{{$faq->FAQQuestion}}"</strong></h2>
                </div>

                <div class="form-group{{ $errors->has('FAQQuestion') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label" for="FAQQuestion">Question</label>

                    <div class="col-md-9">
                    <textarea id="news_content" name="FAQQuestion" rows="9" class="form-control"
                              placeholder="Enter FAQ question..">{!! Request::old('FAQQuestion') ? : $faq->FAQQuestion !!}</textarea>
                        @if($errors->has('FAQQuestion'))
                            <span class="help-block animation-slideDown">{{ $errors->first('FAQQuestion') }}</span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('FAQAnswer') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label" for="FAQAnswer">Answer</label>

                    <div class="col-md-9">
                    <textarea id="news_content" name="FAQAnswer" rows="9" class="form-control"
                              placeholder="Enter FAQ answer..">{!! Request::old('FAQAnswer') ? : $faq->FAQAnswer !!}</textarea>
                        @if($errors->has('FAQAnswer'))
                            <span class="help-block animation-slideDown">{{ $errors->first('FAQAnswer') }}</span>
                        @endif
                    </div>
                </div>


                <div class="form-group{{ $errors->has('FAQVideoTag') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label" for="FAQVideoTag">Video Tag</label>

                    <div class="col-md-9">
                        <input type="text" class="form-control" id="FAQVideoTag" name="FAQVideoTag"
                               value="{{  Request::old('FAQVideoTag') ? : $faq->FAQVideoTag }}"
                               placeholder="Enter Faq video tag..">
                        @if($errors->has('FAQVideoTag'))
                            <span class="help-block animation-slideDown">{{ $errors->first('FAQVideoTag') }}</span>
                        @endif
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-3 control-label">Is Enabled?</label>

                    <div class="col-md-9">
                        <label class="switch switch-primary">
                            <input type="checkbox" id="FAQEnabled" name="FAQEnabled"
                                   value="1" {{ Request::old('FAQEnabled') ? : ($faq->FAQEnabled ? 'checked' : '') }}>
                            <span></span>
                        </label>
                    </div>
                </div>

                <div class="form-group form-actions">
                    <div class="col-md-9 col-md-offset-3">
                        <a href="{{ route('admin.faqs.index', $faq->FAQTypeID) }}" class="btn btn-sm btn-warning">Cancel</a>
                        <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-floppy-o"></i> Save
                        </button>
                    </div>
                </div>
            </div>
        </div>
        {{ Form::close() }}
    </div>
@endsection

@push('extrascripts')
    <script type="text/javascript" src="{{ asset('public/js/ckeditor/ckeditor.js') }}"></script>
    <script type="text/javascript" src="{{ asset('public/js/libraries/faqs.js') }}"></script>
@endpush

resources/views/admin/pages/faq/index.blade.php
@extends('admin.layouts.base')

@section('content')

        <div class="row text-center">
            <div class="col-sm-12 col-lg-12">
               <a href="{{ route('admin.faqs.create',$id) }}" class="widget widget-hover-effect2">
                    <div class="widget-extra themed-background">
                        <h4 class="widget-content-light">
                            <strong>Add New</strong>
                            FAQ
                        </h4>
                    </div>
                    <div class="widget-extra-full">
                        <span class="h2 text-primary animation-expandOpen">
                            <i class="fa fa-plus"></i>
                        </span>
                    </div>
                </a>
            </div>
        </div>

    <div class="block full">
        <div class="block-title">
            <h2>
                <i class="fa fa-newspaper-o sidebar-nav-icon"></i>
                <strong>FAQ's</strong>
            </h2>
        </div>
        <div class="alert alert-info alert-dismissable press-empty {{$faqs->count() == 0 ? '' : 'johnCena' }}">
            <i class="fa fa-info-circle"></i> No FAQ's found.
        </div>
        <div class="table-responsive {{$faqs->count() == 0 ? 'johnCena' : '' }}">
            <table id="faqs-table" class="table table-bordered table-striped table-vcenter">
                <thead>
                <tr role="row">
                    <th class="text-center">
                        ID
                    </th>
                    <th class="text-left">
                        Question
                    </th>
                    <th class="text-left">
                        Answer
                    </th>
                    <th class="text-center">
                        Action
                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach($faqs as $faq)
                    <tr data-faq-id="{{$faq->id}}">
                        <td class="text-center"><strong>{{ $faq->FAQID }}</strong></td>
                        <td class="text-center"><strong>{{ $faq->FAQQuestion }}</strong></td>
                        <td class="text-center">{{ $faq->FAQAnswer }}</td>
                        <td class="text-center">
                            <div class="btn-group btn-group-xs">
                                   <a href="{{ route('admin.faqs.show', $faq->FAQID) }}"
                                       data-toggle="tooltip"
                                       title=""
                                       class="btn btn-default"
                                       data-original-title="View"><i class="fa fa-eye"></i></a>
                                <a href="{{ route('admin.faqs.edit', $faq->FAQID) }}"
                                       data-toggle="tooltip"
                                       title=""
                                       class="btn btn-default"
                                       data-original-title="Edit"><i class="fa fa-pencil"></i></a>
                                    <a href="javascript:void(0)" data-toggle="tooltip"
                                       title=""
                                       class="btn btn-xs btn-danger delete-faq-btn"
                                       data-original-title="Delete"
                                       data-faq-id="{{ $faq->id }}"
                                       data-faq-route="{{ route('admin.faqs.delete', $faq->FAQID) }}">
                                        <i class="fa fa-times"></i>
                                    </a>

                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

@push('extrascripts')
    <script type="text/javascript" src="{{ asset('public/js/libraries/faqs.js') }}"></script>
@endpush

resources/views/admin/pages/faq/show.blade.php
@extends('admin.layouts.base')

@section('content')
    <ul class="breadcrumb breadcrumb-top">
        <li><a href="{{ route('admin.faqs.index', $faq->FAQTypeID) }}">FAQ's</a></li>
        <li><span href="javascript:void(0)">View FAQ</span></li>
    </ul>
    <div class="content-header">
        <div class="header-section">
            <h1>{{ $faq->FAQQuestion }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
            <div class="block block-alt-noborder">
                <article>
                    <h3 class="sub-header text-center"><strong> {{ $faq->FAQCreatedDate}} </strong>
                        <div class="btn-group btn-group-xs pull-right">

                                <a href="{{ route('admin.faqs.edit', $faq->FAQID) }}"
                                   data-toggle="tooltip"
                                   title=""
                                   class="btn btn-default"
                                   data-original-title="Edit"><i class="fa fa-pencil"></i> Edit</a>

                                <a href="javascript:void(0)" data-toggle="tooltip"
                                   title=""
                                   class="btn btn-xs btn-danger delete-faq-btn"
                                   data-original-title="Delete"
                                   data-faq-id="{{ $faq->FAQID }}"
                                   data-faq-route="{{ route('admin.faqs.delete', $faq->FAQID) }}">
                                    <i class="fa fa-times"> Delete</i>
                                </a>

                        </div>
                    </h3>

                    <p>{!! $faq->FAQAnswer !!}</p>
                </article>
            </div>
        </div>
    </div>
@endsection

@push('extrascripts')
    <script type="text/javascript" src="{{ asset('public/js/libraries/faqs.js') }}"></script>
@endpush