routes/admin.php
<?php

/* dashboard routes */
Route::get('/', function () {
    return redirect('/admin/dashboard');
});

/* dashboard */
Route::get('/dashboard', [
    'uses' => '\App\Http\Controllers\AdminDashboardController@index',
    'as' => 'admin.dashboard',
]);
/* dashboard */

/* users */
Route::get('/users/draw',
    ['as' => 'admin.users.draw',
        'uses' => '\App\Http\Controllers\UserController@draw']
);

Route::resource('/users', 'UserController', [
    'as' => 'admin'
]);

Route::delete('/users/{id}/delete',
    ['as' => 'admin.users.delete',
        'uses' => '\App\Http\Controllers\UserController@destroy']
);
/* users */

/* roles */
Route::resource('/roles', 'RoleController', [
    'as' => 'admin'
]);

Route::delete('/roles/{id}/delete',
    ['as' => 'admin.roles.delete',
        'uses' => '\App\Http\Controllers\RoleController@destroy']
);
/* roles */

/* permissions */
Route::resource('/permissions', 'PermissionController', [
    'as' => 'admin'
]);

Route::delete('/permissions/{id}/delete',
    ['as' => 'admin.permissions.delete',
        'uses' => '\App\Http\Controllers\PermissionController@destroy']
);
/* permissions */

/* permission groups */
Route::resource('/permission_groups', 'PermissionGroupController', [
    'as' => 'admin'
]);

Route::delete('/permission_groups/{id}/delete',
    ['as' => 'admin.permission_groups.delete',
        'uses' => '\App\Http\Controllers\PermissionGroupController@destroy']
);
/* permission groups */

/* system settings */
Route::resource('/system_settings', 'SystemSettingController', [
    'as' => 'admin',
]);

Route::delete('/system_settings/{id}/delete',
    ['as' => 'admin.system_settings.delete',
        'uses' => '\App\Http\Controllers\SystemSettingController@destroy']
);
/* system settings */

/* posts */
Route::resource('/posts', 'PostController', [
    'as' => 'admin'
]);

Route::delete('/posts/{id}/delete',
    ['as' => 'admin.posts.delete',
        'uses' => '\App\Http\Controllers\PostController@destroy']
);
/* posts */

/* pages */
Route::resource('/pages', 'PageController', [
    'as' => 'admin'
]);

Route::delete('/pages/{id}/delete',
    ['as' => 'admin.pages.delete',
        'uses' => '\App\Http\Controllers\PageController@destroy']
);
/* pages */

/* ckeditor image upload */
Route::post('/ckeditor_image_upload',
    ['as' => 'admin.ckeditor_image_upload',
        'uses' => '\App\Http\Controllers\PageController@ckEditorImageUpload']
);
/* ckeditor image upload */

Route::post('/upload', '\App\Http\Controllers\PageController@upload')->name('admin.upload');

/* home_slides */
Route::resource('/home_slides', 'HomeSlideController', [
    'as' => 'admin'
]);

Route::delete('/home_slides/{id}/delete',
    ['as' => 'admin.home_slides.delete',
        'uses' => '\App\Http\Controllers\HomeSlideController@destroy']
);
/* home_slides */

/* news_press */
Route::resource('/news_press', 'NewsPressController', [
    'as' => 'admin'
]);

Route::delete('/news_press/{id}/delete',
    ['as' => 'admin.news_press.delete',
        'uses' => '\App\Http\Controllers\NewsPressController@destroy']
);
/* news_press */

/* projct_case_study */
Route::resource('/projct_case_study', 'ProjectCaseController', [
    'as' => 'admin'
]);

Route::delete('/projct_case_study/{id}/delete',
    ['as' => 'admin.projct_case_study.delete',
        'uses' => '\App\Http\Controllers\ProjectCaseController@destroy']
);
/* projct_case_study */

/* ser_sol */
Route::resource('/ser_sol', 'ServiceSolutionController', [
    'as' => 'admin'
]);

Route::delete('/ser_sol/{id}/delete',
    ['as' => 'admin.ser_sol.delete',
        'uses' => '\App\Http\Controllers\ServiceSolutionController@destroy']
);
/* ser_sol */

/* products */
Route::resource('/products', 'ProductController', [
    'as' => 'admin'
]);

Route::delete('/products/{id}/delete',
    ['as' => 'admin.products.delete',
        'uses' => '\App\Http\Controllers\ProductController@destroy']
);
/* products */

/* product categories */
Route::resource('/product_categories', 'ProductCategoryController', [
    'as' => 'admin'
]);

Route::delete('/product_categories/{id}/delete',
    ['as' => 'admin.product_categories.delete',
        'uses' => '\App\Http\Controllers\ProductCategoryController@destroy']
);
/* product categories */

/* contacts */
Route::resource('/contacts', 'ContactController', [
    'as' => 'admin'
]);

Route::delete('/contacts/{id}/delete',
    ['as' => 'admin.contacts.delete',
        'uses' => '\App\Http\Controllers\ContactController@destroy']
);
/* contacts */

/* presses */


/*Route::resource('/faqs', 'FAQController', [
    'as' => 'admin'
]);

*/


/* projects */
        Route::resource('/projects', 'ProjectController', [
            'as' => 'admin'
        ]);

Route::delete('/projects/{id}/delete',
            ['as' => 'admin.projects.delete',
                'uses' => '\App\Http\Controllers\ProjectController@destroy']
        );
        /* projects */

/* services */
        Route::resource('/services', 'ServiceController', [
            'as' => 'admin'
        ]);

Route::delete('/services/{id}/delete',
            ['as' => 'admin.services.delete',
                'uses' => '\App\Http\Controllers\ServiceController@destroy']
        );
        /* services */

/* news */
        Route::resource('/news', 'NewsController', [
            'as' => 'admin'
        ]);

Route::delete('/news/{id}/delete',
            ['as' => 'admin.news.delete',
                'uses' => '\App\Http\Controllers\NewsController@destroy']
        );
        /* news */

/* leaderships */
        Route::resource('/leaderships', 'LeadershipController', [
            'as' => 'admin'
        ]);

Route::delete('/leaderships/{id}/delete',
            ['as' => 'admin.leaderships.delete',
                'uses' => '\App\Http\Controllers\LeadershipController@destroy']
        );
        /* leaderships */

/* newscategories */
        Route::resource('/newscategories', 'NewsCategoryController', [
            'as' => 'admin'
        ]);

Route::delete('/newscategories/{id}/delete',
            ['as' => 'admin.newscategories.delete',
                'uses' => '\App\Http\Controllers\NewsCategoryController@destroy']
        );
        /* newscategories */

routes/web.php
<?php
use Illuminate\Http\Request;
use App\Models\Project;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/re_order_proeject', function(Request $request) {

    $order = $request->data;

    $get_project = new Project();

    // $project_all = $get_project::all();

    $counter = 1;

    foreach($order as $proj)
    {
        $get_project::find($proj)->update(['order' => $counter]);
        $counter++;
    }

    // return $project_all;
    
});

resources/views/admin/pages/page/create.blade.php
@extends('admin.layouts.base')

@section('content')
    <ul class="breadcrumb breadcrumb-top">
        <li><a href="{{ route('admin.pages.index') }}">Pages</a></li>
        <li><span href="javascript:void(0)">Add New Page</span></li>
    </ul>
    <div class="row">
        {{  Form::open([
            'method' => 'POST',
            'id' => 'create-page',
            'route' => ['admin.pages.store'],
            'class' => 'form-horizontal ',
            'files' => TRUE,
            ])
        }}
        <div class="col-md-12">
            <div class="block">
                <div class="block-title">
                    <h2><i class="fa fa-pencil"></i> <strong>Add new Page</strong></h2>
                </div>
                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label" for="pages_name">Name</label>

                    <div class="col-md-9">
                        <input type="text" class="form-control" id="pages_name" name="name"
                               placeholder="Enter page name.." value="{{ old('name') }}">
                        @if($errors->has('name'))
                            <span class="help-block animation-slideDown">{{ $errors->first('name') }}</span>
                        @endif
                    </div>
                </div>
                <div class="form-group{{ $errors->has('slug') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label" for="pages_slug">Slug</label>

                    <div class="col-md-9">
                        <input type="text" class="form-control" id="pages_slug" name="slug"
                               placeholder="Enter page slug.." value="{{ old('slug') }}">
                        @if($errors->has('slug'))
                            <span class="help-block animation-slideDown">{{ $errors->first('slug') }}</span>
                        @endif
                    </div>
                </div>


                <div class="form-group{{ $errors->has('banner_image') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label" for="file">Banner Image</label>
                    <div class="col-md-9">
                        <div class="input-group">
                            <label class="input-group-btn">
                        <span class="btn btn-primary">
                            Choose File <input type="file" class="form-control" name="banner_image" style="display: none;">
                            <input type="hidden" class="fld" name="banner_image" value="">
                        </span>
                            </label>
                            <input type="text" class="form-control" readonly>
                        </div>
                        @if($errors->has('banner_image'))
                            <span class="help-block animation-slideDown">{{ $errors->first('banner_image') }}</span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('page_type') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label" for="page_type_id">Type</label>

                    <div class="col-md-9">
                        <select name="page_type_id" id="page_type_id"
                                class="page-type-select"
                                data-placeholder="Choose page type..">
                            <option value=""></option>
                            @foreach($page_types as $page_type)
                                <option value="{{ $page_type->id }}" {{ old('page_type_id') ? old('page_type_id') == $page_type->id ? 'selected' : '' : '' }}>{{ $page_type->name }}</option>
                            @endforeach
                        </select>
                        @if($errors->has('page_type'))
                            <span class="help-block animation-slideDown">{{ $errors->first('page_type') }}</span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('content') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label" for="page_content">Content</label>

                    <div class="col-md-9">
                            <textarea id="page_content" name="content" rows="9"
                                      class="form-control ckeditor"
                                      placeholder="Enter page content..">{{ old('content') }}</textarea>
                        @if($errors->has('content'))
                            <span class="help-block animation-slideDown">{{ $errors->first('content') }}</span>
                        @endif
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Is Active?</label>

                    <div class="col-md-9">
                        <label class="switch switch-primary">
                            <input type="checkbox" id="is_active" name="is_active"
                                   value="1" checked>
                            <span></span>
                        </label>
                    </div>
                </div>
                <div class="form-group form-actions">
                    <div class="col-md-9 col-md-offset-3">
                        <a href="{{ route('admin.pages.index') }}" class="btn btn-sm btn-warning">Cancel</a>
                        <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-floppy-o"></i> Save
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            @include('admin.pages.page.meta_fields')
        </div>
        {{ Form::close() }}
    </div>
@endsection

@push('extrascripts')
<script type="text/javascript" src="{{ asset('public/js/ckeditor/ckeditor.js') }}"></script>
<script type="text/javascript" src="{{ asset('public/js/libraries/pages.js') }}"></script>
@endpush

resources/views/admin/pages/page/edit.blade.php
@extends('admin.layouts.base')

@section('content')
    <ul class="breadcrumb breadcrumb-top">
        <li><a href="{{ route('admin.pages.index') }}">Pages</a></li>
        <li><span href="javascript:void(0)">Edit Page</span></li>
    </ul>
    <div class="row">
        {{  Form::open([
            'method' => 'PUT',
            'id' => 'edit-page',
            'route' => ['admin.pages.update', $page->id],
            'class' => 'form-horizontal ',
            'files' => TRUE,
            ])
        }}
        <div class="col-md-12">
            <div class="block">
                <div class="block-title">
                    <h2><i class="fa fa-pencil"></i> <strong>Edit Page "{{$page->name}}"</strong></h2>
                </div>
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h4 style="border-left: 3px solid #61dbd5; padding-left: 8px; margin-bottom: 20px;">Page Details</h4>
                    </div>
                </div>
                <div id="section-page">
                    @include('admin.components.text', ['field' => 'name', 'label' => 'Name', 'value' => Request::old('name') ?: $page->name])
                    @include('admin.components.text', ['field' => 'slug', 'label' => 'Slug', 'value' => Request::old('slug') ?: $page->slug])

                    @if($page->id != 1)
                        {{-- @include('admin.components.attachment', ['field' => 'banner_image', 'label' => 'Banner Image', 'value' => $page->attachment]) --}}
                    @endif

                    @if($page->content != '---')
                        {{-- @include('admin.components.editor', ['field' => 'content', 'label' => 'Content', 'value' => $page->content]) --}}
                        <input type="hidden" name="content" value="{{ $page->content }}">
                    @else
                        <input type="hidden" name="content" value="{{ $page->content }}">
                    @endif

                </div>

                {{--  Home Page --}}
                @if($page->id == 1)
                <div style="display: none">
                    @include('admin.pages.page.added_pages.home_page')
                </div>
                @elseif($page->id == 2)
                <div style="display: none">
                    @include('admin.pages.page.added_pages.about-us_page')
                </div>
                @elseif($page->id == 3)
                <div style="display: none">
                    @include('admin.pages.page.added_pages.contact-us_page')
                </div>
                @elseif($page->id == 9)
                <div style="display: none">
                    @include('admin.pages.page.added_pages.news_page')
                </div>
                @elseif($page->id == 13)
                <div style="display: none">
                    @include('admin.pages.page.added_pages.project_page')
                </div>
                @elseif($page->id == 11)
                <div style="display: none">
                    @include('admin.pages.page.added_pages.services_page')
                </div>
                @elseif($page->id == 16)
                <div style="display: none">
                    @include('admin.pages.page.added_pages.renewable_page')
                </div>
                @elseif($page->id == 14)
                <div style="display: none">
                    @include('admin.pages.page.added_pages.team_page')
                </div>
                @elseif($page->id == 15)
                <div style="display: none">
                    @include('admin.pages.page.added_pages.team-details_page')
                </div>
                @else
                    @include('admin.components.attachment', ['field' => 'banner_image', 'label' => 'Banner Image', 'value' => $page->banner_image])
                    @include('admin.components.editor', ['field' => 'content', 'label' => 'Content', 'value' => $page->content])
                @endif

                @include('admin.pages.page.page_sections')

                
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <div class="form-group">
                            <label class="col-md-2 control-label">Is Active?</label>

                            <div class="col-md-10">
                                <label class="switch switch-primary">
                                    <input type="checkbox" id="is_active" name="is_active"
                                           value="1" {{ Request::old('is_active') ? : ($page->is_active ? 'checked' : '') }}>
                                    <span></span>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group form-actions">
                    <div class="col-md-9 col-md-offset-3">
                        <a href="{{ route('admin.pages.index') }}" class="btn btn-sm btn-warning">Cancel</a>
                        <button id="btnSave" type="submit" class="btn btn-sm btn-primary"><i class="fa fa-floppy-o"></i> Save</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            @include('admin.pages.page.meta_fields',['seo_meta_fields'=>$page->seoMeta])
        </div>
        {{ Form::close() }}
    </div>
@endsection

@push('extrascripts')
<script type="text/javascript" src="{{ asset('public/js/ckeditor/ckeditor.js') }}"></script>
<script type="text/javascript" src="{{ asset('public/js/libraries/pages.js') }}"></script>
<script>
    $('input[type=file].async').each(function (i, el) {
        var $self = $(this);
        $(el).on('change', function (e) {
            if (e.target.files.length === 0)
                return;

            var formData = new FormData();
            formData.append('image', e.target.files[0]);
            formData.append('_token', '{{ csrf_token() }}');

            $.ajax({
                type: 'POST',
                url: '{{ route('admin.upload') }}',
                data: formData,
                contentType: false,
                cache: false,
                processData: false,
                success: function (response) {
                    if (response.status) {
                        $self.siblings('input[type=hidden].fld').val(response.data.id);
                    }
                }
            });
        });
    });

    var sections = {!! json_encode($page->sections) !!}.map(function (section) {
        if (section.type === 3)
            section.value = JSON.parse(section.value);
        return section;
    });

    $('#btnSave').on('click', function (e) {
        e.preventDefault();

        sections.filter(function (section) {
            return section.type === 3;
        }).forEach(function (section) {
            section.value.data = $(`#section-${section.id}`).children('.form-field').map(function (i, el) {
                return $(el).find('.form-group').toArray().reduce(function (item, fg) {
                    var field = $(fg).find('input.fld');

                    if (field.length > 0) {
                        item[$(field).data('name')] = $(field).val();
                    } else if (field.length === 0) {
                        field = $(fg).find('textarea.fld');

                        if (field.length > 0) {
                            var editor = CKEDITOR.instances[field.attr('id')];

                            if (editor) {
                                item[$(field).data('name')] = editor.getData();
                            } else {
                                item[$(field).data('name')] = $(field).val();
                            }
                        }
                    }

                    return item;
                }, {});
            }).toArray();
            $(`input[name=${section.alias}]`).val(JSON.stringify(section.value));
        });

        $('form#edit-page').submit();
    });
</script>
@endpush

resources/views/admin/pages/page/index.blade.php
@extends('admin.layouts.base')

@section('content')
    @if (auth()->user()->can('Create Page'))
        <div class="row text-center">
            <div class="col-sm-12 col-lg-12">
                <a href="{{ route('admin.pages.create') }}" class="widget widget-hover-effect2">
                    <div class="widget-extra themed-background">
                        <h4 class="widget-content-light"><strong>Add New</strong> Page</h4>
                    </div>
                    <div class="widget-extra-full"><span class="h2 text-primary animation-expandOpen"><i
                                    class="fa fa-plus"></i></span></div>
                </a>
            </div>
        </div>
    @endif
    <div class="block full">
        <div class="block-title">
            <h2><i class="fa fa-archive sidebar-nav-icon"></i>&nbsp;<strong>Pages</strong></h2>
        </div>
        <div class="alert alert-info alert-dismissable page-empty {{$pages->count() == 0 ? '' : 'johnCena' }}">
            <i class="fa fa-info-circle"></i> No pages found.
        </div>
        <div class="table-responsive {{$pages->count() == 0 ? 'johnCena' : '' }}">
            <table id="pages-table"
                   class="table table-bordered table-striped table-vcenter">
                <thead>
                <tr role="row">
                    <th class="text-center">
                        ID
                    </th>
                    <th class="text-left">
                        Name
                    </th>
                    <th class="text-left">
                        Slug
                    </th>
                    {{--<th class="text-left">--}}
                    {{--Type--}}
                    {{--</th>--}}
                    <th class="text-center">
                        Action
                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach($pages as $page)
                    <tr data-page-template-id="{{$page->id}}">
                        <td class="text-center">{{ $page->id }}</td>
                        <td class="text-left">{{ $page->name }}</td>
                        <td class="text-left"><a href="{{ url($page->slug) }}" target="_blank">{{ url($page->slug) }}</a></td>
                        {{--<td class="text-left">{{ $page->page_type->name }}</td>--}}
                        <td class="text-center">
                            <div class="btn-group btn-group-xs">
                                @if (auth()->user()->can('Update Page'))
                                    <a href="{{ route('admin.pages.edit', $page->id) }}"
                                       data-toggle="tooltip"
                                       title=""
                                       class="btn btn-default"
                                       data-original-title="Edit"><i class="fa fa-pencil"></i></a>
                                @endif
                                @if (auth()->user()->can('Delete Page'))
                                    <a href="javascript:void(0)" data-toggle="tooltip"
                                       title=""
                                       class="btn btn-xs btn-danger delete-page-btn"
                                       data-original-title="Delete"
                                       data-page-id="{{ $page->id }}"
                                       data-page-route="{{ route('admin.pages.destroy', $page->id) }}">
                                        <i class="fa fa-times"></i>
                                    </a>
                                @endif
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

@push('extrascripts')
<script type="text/javascript" src="{{ asset('public/js/libraries/pages.js') }}"></script>
@endpush

resources/views/admin/pages/page/meta_fields.blade.php
<div class="block">
    <div class="block-title">
        <h2><i class="fa fa-archive"></i> <strong>Meta Data</strong></h2>
    </div>
    <input type="hidden" name="seo_meta_id" value="{{ (!empty($page) ? $page->seo_meta_id : 0) }}">
    <div class="form-group{{ $errors->has('meta_title') ? ' has-error' : '' }}">
        <label class="col-md-3 control-label" for="meta_title">Meta Title</label>

        <div class="col-md-9">
            <input type="text" class="form-control" id="meta_title" name="meta_title"
                   value="{{ Request::old('meta_title') ? old('meta_title') : (!empty($seo_meta_fields) ? $seo_meta_fields->meta_title : '') }}"
                   placeholder="Enter meta title..">
            @if($errors->has('meta_title'))
                <span class="help-block animation-slideDown">{{ $errors->first('meta_title') }}</span>
            @endif
        </div>
    </div>
    <div class="form-group{{ $errors->has('meta_keywords') ? ' has-error' : '' }}">
        <label class="col-md-3 control-label" for="meta_keywords">Meta Keywords</label>

        <div class="col-md-9">
            <input type="text" class="form-control" id="meta_keywords" name="meta_keywords"
                   value="{{ Request::old('meta_keywords') ? old('meta_keywords') : (!empty($seo_meta_fields) ? $seo_meta_fields->meta_keywords : '') }}"
                   placeholder="Enter meta keywords..">
            @if($errors->has('meta_keywords'))
                <span class="help-block animation-slideDown">{{ $errors->first('meta_keywords') }}</span>
            @endif
        </div>
    </div>
    <div class="form-group{{ $errors->has('meta_description') ? ' has-error' : '' }}">
        <label class="col-md-3 control-label" for="meta_description">Meta Description</label>

        <div class="col-md-9">
                <textarea class="form-control" id="meta_description" name="meta_description"
                          placeholder="Enter meta description.." style="resize: vertical; min-height: 100px;"
                          rows="5">{{ Request::old('meta_description') ? old('meta_description') : (!empty($seo_meta_fields) ? $seo_meta_fields->meta_description : '') }}</textarea>
            @if($errors->has('meta_description'))
                <span class="help-block animation-slideDown">{{ $errors->first('meta_description') }}</span>
            @endif
        </div>
    </div>
</div>