routes/admin.php
<?php

/* dashboard routes */
Route::get('/', function () {
    return redirect('/admin/dashboard');
});

/* dashboard */
Route::get('/dashboard', [
    'uses' => '\App\Http\Controllers\AdminDashboardController@index',
    'as' => 'admin.dashboard',
]);
/* dashboard */

/* users */
Route::get('/users/draw',
    ['as' => 'admin.users.draw',
        'uses' => '\App\Http\Controllers\UserController@draw']
);

Route::resource('/users', 'UserController', [
    'as' => 'admin'
]);

Route::delete('/users/{id}/delete',
    ['as' => 'admin.users.delete',
        'uses' => '\App\Http\Controllers\UserController@destroy']
);
/* users */

/* roles */
Route::resource('/roles', 'RoleController', [
    'as' => 'admin'
]);

Route::delete('/roles/{id}/delete',
    ['as' => 'admin.roles.delete',
        'uses' => '\App\Http\Controllers\RoleController@destroy']
);
/* roles */

/* permissions */
Route::resource('/permissions', 'PermissionController', [
    'as' => 'admin'
]);

Route::delete('/permissions/{id}/delete',
    ['as' => 'admin.permissions.delete',
        'uses' => '\App\Http\Controllers\PermissionController@destroy']
);
/* permissions */

/* permission groups */
Route::resource('/permission_groups', 'PermissionGroupController', [
    'as' => 'admin'
]);

Route::delete('/permission_groups/{id}/delete',
    ['as' => 'admin.permission_groups.delete',
        'uses' => '\App\Http\Controllers\PermissionGroupController@destroy']
);
/* permission groups */

/* system settings */
Route::resource('/system_settings', 'SystemSettingController', [
    'as' => 'admin',
]);

Route::delete('/system_settings/{id}/delete',
    ['as' => 'admin.system_settings.delete',
        'uses' => '\App\Http\Controllers\SystemSettingController@destroy']
);
/* system settings */

/* posts */
Route::resource('/posts', 'PostController', [
    'as' => 'admin'
]);

Route::delete('/posts/{id}/delete',
    ['as' => 'admin.posts.delete',
        'uses' => '\App\Http\Controllers\PostController@destroy']
);
/* posts */

/* pages */
Route::resource('/pages', 'PageController', [
    'as' => 'admin'
]);

Route::delete('/pages/{id}/delete',
    ['as' => 'admin.pages.delete',
        'uses' => '\App\Http\Controllers\PageController@destroy']
);
/* pages */

/* ckeditor image upload */
Route::post('/ckeditor_image_upload',
    ['as' => 'admin.ckeditor_image_upload',
        'uses' => '\App\Http\Controllers\PageController@ckEditorImageUpload']
);
/* ckeditor image upload */

Route::post('/upload', '\App\Http\Controllers\PageController@upload')->name('admin.upload');

/* home_slides */
Route::resource('/home_slides', 'HomeSlideController', [
    'as' => 'admin'
]);

Route::delete('/home_slides/{id}/delete',
    ['as' => 'admin.home_slides.delete',
        'uses' => '\App\Http\Controllers\HomeSlideController@destroy']
);
/* home_slides */

/* news_press */
Route::resource('/news_press', 'NewsPressController', [
    'as' => 'admin'
]);

Route::delete('/news_press/{id}/delete',
    ['as' => 'admin.news_press.delete',
        'uses' => '\App\Http\Controllers\NewsPressController@destroy']
);
/* news_press */

/* projct_case_study */
Route::resource('/projct_case_study', 'ProjectCaseController', [
    'as' => 'admin'
]);

Route::delete('/projct_case_study/{id}/delete',
    ['as' => 'admin.projct_case_study.delete',
        'uses' => '\App\Http\Controllers\ProjectCaseController@destroy']
);
/* projct_case_study */

/* ser_sol */
Route::resource('/ser_sol', 'ServiceSolutionController', [
    'as' => 'admin'
]);

Route::delete('/ser_sol/{id}/delete',
    ['as' => 'admin.ser_sol.delete',
        'uses' => '\App\Http\Controllers\ServiceSolutionController@destroy']
);
/* ser_sol */

/* products */
Route::resource('/products', 'ProductController', [
    'as' => 'admin'
]);

Route::delete('/products/{id}/delete',
    ['as' => 'admin.products.delete',
        'uses' => '\App\Http\Controllers\ProductController@destroy']
);
/* products */

/* product categories */
Route::resource('/product_categories', 'ProductCategoryController', [
    'as' => 'admin'
]);

Route::delete('/product_categories/{id}/delete',
    ['as' => 'admin.product_categories.delete',
        'uses' => '\App\Http\Controllers\ProductCategoryController@destroy']
);
/* product categories */

/* contacts */
Route::resource('/contacts', 'ContactController', [
    'as' => 'admin'
]);

Route::delete('/contacts/{id}/delete',
    ['as' => 'admin.contacts.delete',
        'uses' => '\App\Http\Controllers\ContactController@destroy']
);
/* contacts */

/* presses */


/*Route::resource('/faqs', 'FAQController', [
    'as' => 'admin'
]);

*/


/* projects */
        Route::resource('/projects', 'ProjectController', [
            'as' => 'admin'
        ]);

Route::delete('/projects/{id}/delete',
            ['as' => 'admin.projects.delete',
                'uses' => '\App\Http\Controllers\ProjectController@destroy']
        );
        /* projects */

/* services */
        Route::resource('/services', 'ServiceController', [
            'as' => 'admin'
        ]);

Route::delete('/services/{id}/delete',
            ['as' => 'admin.services.delete',
                'uses' => '\App\Http\Controllers\ServiceController@destroy']
        );
        /* services */

/* news */
        Route::resource('/news', 'NewsController', [
            'as' => 'admin'
        ]);

Route::delete('/news/{id}/delete',
            ['as' => 'admin.news.delete',
                'uses' => '\App\Http\Controllers\NewsController@destroy']
        );
        /* news */

/* leaderships */
        Route::resource('/leaderships', 'LeadershipController', [
            'as' => 'admin'
        ]);

Route::delete('/leaderships/{id}/delete',
            ['as' => 'admin.leaderships.delete',
                'uses' => '\App\Http\Controllers\LeadershipController@destroy']
        );
        /* leaderships */

/* newscategories */
        Route::resource('/newscategories', 'NewsCategoryController', [
            'as' => 'admin'
        ]);

Route::delete('/newscategories/{id}/delete',
            ['as' => 'admin.newscategories.delete',
                'uses' => '\App\Http\Controllers\NewsCategoryController@destroy']
        );
        /* newscategories */

routes/web.php
<?php
use Illuminate\Http\Request;
use App\Models\Project;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/re_order_proeject', function(Request $request) {

    $order = $request->data;

    $get_project = new Project();

    // $project_all = $get_project::all();

    $counter = 1;

    foreach($order as $proj)
    {
        $get_project::find($proj)->update(['order' => $counter]);
        $counter++;
    }

    // return $project_all;
    
});

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class News
 * @package App\Models
 * @author Randall Anthony Bondoc
 */
class News extends Model
{
    use SoftDeletes;

    protected $table = 'news';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'date',
        'link',
        'category_id',
        'slug',
        'banner_image',
        'file',
        'content_1',
        'content_2',
        'is_active',
    ];

    public function news_category()
    {
       return $this->belongsTo('\App\Models\NewsCategory','category_id');
    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\News;
use App\Repositories\NewsRepository;

/**
 * Class NewsController
 * @package App\Http\Controllers
 * @author Randall Anthony Bondoc
 */
class NewsController extends Controller
{
    /**
     * News model instance.
     *
     * @var News
     */
    private $news_model;

    /**
     * NewsRepository repository instance.
     *
     * @var NewsRepository
     */
    private $news_repository;

    /**
     * Create a new controller instance.
     *
     * @param News $news_model
     * @param NewsRepository $news_repository
     */
    public function __construct(News $news_model, NewsRepository $news_repository)
    {
        /*
         * Model namespace
         * using $this->news_model can also access $this->news_model->where('id', 1)->get();
         * */
        $this->news_model = $news_model;

        /*
         * Repository namespace
         * this class may include methods that can be used by other controllers, like getting of news with other data (related tables).
         * */
        $this->news_repository = $news_repository;

//        $this->middleware(['isAdmin']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        if (!auth()->user()->hasPermissionTo('Read News')) {
            abort('401', '401');
        }

        $news = $this->news_model->get();

        return view('admin.pages.news.index', compact('news'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (!auth()->user()->hasPermissionTo('Create News')) {
            abort('401', '401');
        }

        return view('admin.pages.news.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        if (!auth()->user()->hasPermissionTo('Create News')) {
            abort('401', '401');
        }

        $this->validate($request, [
            'name' => 'required|unique:news,name,NULL,id,deleted_at,NULL',
            // 'slug' => 'required|unique:news,slug,NULL,id,deleted_at,NULL',
            'content_1' => 'required',
            'banner_image' => 'mimes:jpg,jpeg,png',
            // 'file' => 'mimes:docx,doc,pdf',
        ]);

        $input = $request->all();
        $input['is_active'] = isset($input['is_active']) ? 1 : 0;
        /* if slug is hidden, generate slug automatically */
        $input['slug'] = str_slug($input['name']);

        $news = $this->news_model->create($input);

        if ($request->hasFile('banner_image')) {
            $file_upload_path = $this->news_repository->uploadFile($request->file('banner_image'), /*'banner_image'*/null, 'news_images');
            $news->fill(['banner_image' => $file_upload_path])->save();
        }
        // if ($request->hasFile('file')) {
        //     $file_upload_path = $this->news_repository->uploadFile($request->file('file'), /*'file'*/null, 'news_files');
        //     $news->fill(['file' => $file_upload_path])->save();
        // }

        return redirect()->route('admin.news.index')->with('flash_message', [
            'title' => '',
            'message' => 'News ' . $news->name . ' successfully added.',
            'type' => 'success'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (!auth()->user()->hasPermissionTo('Read News')) {
            abort('401', '401');
        }

        $news = $this->news_model->findOrFail($id);

        return view('admin.pages.news.show', compact('news'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (!auth()->user()->hasPermissionTo('Update News')) {
            abort('401', '401');
        }

        $news = $this->news_model->findOrFail($id);

        return view('admin.pages.news.edit', compact('news'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, $id)
    {
        if (!auth()->user()->hasPermissionTo('Update News')) {
            abort('401', '401');
        }

        $this->validate($request, [
            'name' => 'required',
            // 'slug' => 'required|unique:news,slug,' . $id . ',id,deleted_at,NULL',
            'content_1' => 'required',
            'banner_image' => 'required_if:remove_banner_image,==,1|mimes:jpg,jpeg,png',
            // 'file' => 'required_if:remove_file,==,1|mimes:docx,doc,pdf',
        ]);

        $news = $this->news_model->findOrFail($id);
        $input = $request->all();
        $input['is_active'] = isset($input['is_active']) ? 1 : 0;
        /* if slug is hidden, generate slug automatically */
        $input['slug'] = str_slug($input['name']);

        if ($request->hasFile('banner_image')) {
            $file_upload_path = $this->news_repository->uploadFile($request->file('banner_image'), /*'banner_image'*/null, 'news_images');
            $input['banner_image'] = $file_upload_path;
        }
        if ($request->has('remove_banner_image') && $request->get('remove_banner_image')) {
            $input['banner_image'] = '';
        }

        // if ($request->hasFile('file')) {
        //     $file_upload_path = $this->news_repository->uploadFile($request->file('file'), /*'file'*/null, 'news_files');
        //     $input['file'] = $file_upload_path;
        // }
        // if ($request->has('remove_file') && $request->get('remove_file')) {
        //     $input['file'] = '';
        // }

        $news->fill($input)->save();

        return redirect()->route('admin.news.index')->with('flash_message', [
            'title' => '',
            'message' => 'News ' . $news->name . ' successfully updated.',
            'type' => 'success'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!auth()->user()->hasPermissionTo('Delete News')) {
            abort('401', '401');
        }

        $news = $this->news_model->findOrFail($id);
        $news->delete();

        $response = array(
            'status' => FALSE,
            'data' => array(),
            'message' => array(),
        );

        $response['message'][] = 'News successfully deleted.';
        $response['data']['id'] = $id;
        $response['status'] = TRUE;

        return response()->json($response);
    }
}

resources/views/admin/pages/news/index.blade.php
@extends('admin.layouts.base')

@section('content')
    @if (auth()->user()->can('Create News'))
        <div class="row text-center">
            <div class="col-sm-12 col-lg-12">
                <a href="{{ route('admin.news.create') }}" class="widget widget-hover-effect2">
                    <div class="widget-extra themed-background">
                        <h4 class="widget-content-light">
                            <strong>Add New</strong>
                            News
                        </h4>
                    </div>
                    <div class="widget-extra-full">
                        <span class="h2 text-primary animation-expandOpen">
                            <i class="fa fa-plus"></i>
                        </span>
                    </div>
                </a>
            </div>
        </div>
    @endif
    <div class="block full">
        <div class="block-title">
            <h2>
                <i class="fa fa-newspaper-o sidebar-nav-icon"></i>
                <strong>News</strong>
            </h2>
        </div>
        <div class="alert alert-info alert-dismissable news-empty {{$news->count() == 0 ? '' : 'johnCena' }}">
            <i class="fa fa-info-circle"></i> No News found.
        </div>
        <div class="table-responsive {{$news->count() == 0 ? 'johnCena' : '' }}">
            <table id="news-table" class="table table-bordered table-striped table-vcenter">
                <thead>
                <tr role="row">
                    <th class="text-center">
                        ID
                    </th>
                    <th class="text-center">
                        Name
                    </th>
                    <th class="text-left">
                        Slug
                    </th>
                    <th class="text-left">
                        Content
                    </th>
                    <th class="text-center">
                        Date Created
                    </th>
                    <th class="text-center">
                        Action
                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach($news as $news)
                    <tr data-news-id="{{$news->id}}">
                        <td class="text-center"><strong>{{ $news->id }}</strong></td>
                        <td class="text-center"><strong>{{ $news->name }}</strong></td>
                        <td class="text-left">
                            @if($news->slug && $news->slug != '')
                                <a target="_blank" href="{{ url('news-details/'.$news->slug) }}">{{ url('news-details/'.$news->slug) }}</a>
                            @endif
                        </td>
                        <td class="text-left">{!! str_limit(strip_tags($news->content_1), 50) !!}</td>
                        <td class="text-center">{{ $news->created_at->format('F d, Y') }}</td>
                        <td class="text-center">
                            <div class="btn-group btn-group-xs">
                                @if (auth()->user()->can('Read News'))
                                    {{-- <a href="{{ route('admin.news.show', $news->id) }}"
                                       data-toggle="tooltip"
                                       title=""
                                       class="btn btn-default"
                                       data-original-title="View"><i class="fa fa-eye"></i></a> --}}
                                @endif
                                @if (auth()->user()->can('Update News'))
                                    <a href="{{ route('admin.news.edit', $news->id) }}"
                                       data-toggle="tooltip"
                                       title=""
                                       class="btn btn-default"
                                       data-original-title="Edit"><i class="fa fa-pencil"></i></a>
                                @endif
                                @if (auth()->user()->can('Delete News'))
                                    <a href="javascript:void(0)" data-toggle="tooltip"
                                       title=""
                                       class="btn btn-xs btn-danger delete-news-btn"
                                       data-original-title="Delete"
                                       data-news-id="{{ $news->id }}"
                                       data-news-route="{{ route('admin.news.delete', $news->id) }}">
                                        <i class="fa fa-times"></i>
                                    </a>
                                @endif
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

@push('extrascripts')
    <script type="text/javascript" src="{{ asset('public/js/libraries/news.js') }}"></script>
@endpush

resources/views/admin/pages/news/show.blade.php
@extends('admin.layouts.base')

@section('content')
    <ul class="breadcrumb breadcrumb-top">
        <li><a href="{{ route('admin.news.index') }}">News</a></li>
        <li><span href="javascript:void(0)">View News</span></li>
    </ul>
    <div class="content-header">
        <div class="header-section">
            <h1>{{ $news->name }}</h1>
            <h5>{{ $news->slug }}</h5>
        </div>
    </div>
    <div class="row">
        <div class="col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
            <div class="block block-alt-noborder">
                <article>
                    <h3 class="sub-header text-center"><strong> {{ $news->created_at->format('F d, Y') }} </strong>
                        <div class="btn-group btn-group-xs pull-right">
                            @if (auth()->user()->can('Update News'))
                                <a href="{{ route('admin.news.edit', $news->id) }}"
                                   data-toggle="tooltip"
                                   title=""
                                   class="btn btn-default"
                                   data-original-title="Edit"><i class="fa fa-pencil"></i> Edit</a>
                            @endif
                            @if (auth()->user()->can('Delete News'))
                                <a href="javascript:void(0)" data-toggle="tooltip"
                                   title=""
                                   class="btn btn-xs btn-danger delete-news-btn"
                                   data-original-title="Delete"
                                   data-news-id="{{ $news->id }}"
                                   data-news-route="{{ route('admin.news.delete', $news->id) }}">
                                    <i class="fa fa-times"> Delete</i>
                                </a>
                            @endif
                        </div>
                    </h3>

                    <img src="{{ asset($news->banner_image) }}" alt="{{ $news->banner_image }}" class="img-responsive center-block" style="max-width: 100px;">

                    <p>{!! $news->content !!}</p>
                </article>
            </div>
        </div>
    </div>
@endsection

@push('extrascripts')
    <script type="text/javascript" src="{{ asset('public/js/libraries/news.js') }}"></script>
@endpush